import igsRequest from './instance';
// import axios from 'axios';

export const getAdList = async () => {
  // return {
  //   code: 'A00000',
  //   message: 'Success.',
  //   result: [
  //     {
  //       id: 368,
  //       name: 'web home',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'web',
  //       position: 'homepage',
  //       length: 100,
  //       width: 992,
  //       status: 0,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/992x100-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: 'igscore',
  //       createdBy: 'igscore',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 380,
  //       name: 'iOS live',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'ios',
  //       position: 'liveMatch',
  //       length: 100,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x88-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: 'igAdmin',
  //       createdBy: 'igAdmin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 389,
  //       name: 'android live',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'android',
  //       position: 'openScreen',
  //       length: 1160,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x1160-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: 'igAdmin',
  //       createdBy: 'igAdmin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 390,
  //       name: 'mobile home',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'mobile',
  //       position: 'liveTop',
  //       length: 88,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x88-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: 'igAdmin',
  //       createdBy: 'igAdmin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 444,
  //       name: 'web topBanner',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'web',
  //       position: 'topBanner',
  //       length: 90,
  //       width: 1200,
  //       status: 0,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/1200x90-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 445,
  //       name: 'web sidebar',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'web',
  //       position: 'sideBanner',
  //       length: 200,
  //       width: 200,
  //       status: 0,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/200x200-01.jpg',
  //       jumpUrl: '',
  //       description: '',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 493,
  //       name: 'android open',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'android',
  //       position: 'openScreen',
  //       length: 1160,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x1160-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 495,
  //       name: 'ios open',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'ios',
  //       position: 'openScreen',
  //       length: 1160,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x1160-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 496,
  //       name: 'android live bottom',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'android',
  //       position: 'openScreen',
  //       length: 1160,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x1160-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 497,
  //       name: 'android match chat tab',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'android',
  //       position: 'openScreen',
  //       length: 1160,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x88-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 498,
  //       name: 'android match odds bottom',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'android',
  //       position: 'openScreen',
  //       length: 1160,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x88-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 499,
  //       name: 'android match overview tab',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'android',
  //       position: 'openScreen',
  //       length: 1160,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x56-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 500,
  //       name: 'android match sidebar',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'android',
  //       position: 'openScreen',
  //       length: 1160,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/512x56-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 501,
  //       name: 'ios live bottom',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'ios',
  //       position: 'liveBottom',
  //       length: 100,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x88-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 502,
  //       name: 'ios match chat tab',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'ios',
  //       position: 'matchChatTab',
  //       length: 88,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x88-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 503,
  //       name: 'ios match odds bottom',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'ios',
  //       position: 'matchOddsBottom',
  //       length: 88,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x88-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 504,
  //       name: 'ios match overview bottom',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'ios',
  //       position: 'matchOverviewBottom',
  //       length: 88,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x88-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 505,
  //       name: 'ios match overview tab',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'ios',
  //       position: 'matchOverviewTab',
  //       length: 56,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x56-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 506,
  //       name: 'ios match sidebar',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'ios',
  //       position: 'sidebarBottom',
  //       length: 56,
  //       width: 512,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/512x56-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 515,
  //       name: 'mobile match bottom',
  //       country: 'CN',
  //       client: '123',
  //       platform: 'mobile',
  //       position: 'matchPageBottom',
  //       length: 88,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x88-01.jpg',
  //       jumpUrl: '',
  //       description: '',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 904,
  //       name: 'android match overview bottom',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'android',
  //       position: 'openScreen',
  //       length: 1160,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x88-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: '',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 905,
  //       name: 'ios match overview bottom',
  //       country: 'MY',
  //       client: '123',
  //       platform: 'ios',
  //       position: 'openScreen',
  //       length: 1160,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x1160-01.jpg',
  //       jumpUrl: 'https://www.interwinvip.com/',
  //       description: '',
  //       modifiedBy: null,
  //       createdBy: 'admin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //   ],
  //   server_time: 1678192940,
  // };
  return igsRequest.get('user/ad/list');
};

export const goLogin = async ({ username, password }: any) => {
  return igsRequest.post(`doLogin?username=${username}&password=${password}`);
};

export const createAd = async (params: any) => {
  return igsRequest.post(
    'user/ad/create',
    Object.assign(params, {
      client: '123',
      createdBy: 'admin',
    }),
  );
};

export const updateAd = async (params: any) => {
  return igsRequest.post(
    'user/ad/update',
    Object.assign(params, {
      client: '123',
      modifiedBy: 'admin',
    }),
  );
};

export const getAdDetail = async (id: string) => {
  // return {
  //   code: 'A00000',
  //   message: 'Success.',
  //   result: {
  //     id: 380,
  //     name: 'iOS live',
  //     country: 'MY',
  //     client: '123',
  //     platform: 'ios',
  //     position: 'liveMatch',
  //     length: 100,
  //     width: 750,
  //     status: 1,
  //     imageUrl: 'https://files.sitestatic.net/livescore/uploaded/750x88-01.jpg',
  //     jumpUrl: 'https://www.interwinvip.com',
  //     description: 'banner',
  //     modifiedBy: 'igAdmin',
  //     createdBy: 'igAdmin',
  //     startTime: null,
  //     endTime: null,
  //   },
  //   server_time: 1678192900,
  // };
  return igsRequest.get(`user/ad/${id}`);
};

export const goLogout = async () => {
  return igsRequest.post('logout');
};
