import igsRequest from './instance';
// import axios from 'axios';

export const getAdList = async () => {
  // return {
  //   code: 'A00000',
  //   message: 'Success.',
  //   result: [
  //     {
  //       id: 280,
  //       name: null,
  //       country: null,
  //       client: null,
  //       platform: null,
  //       position: null,
  //       length: null,
  //       width: null,
  //       status: 0,
  //       imageUrl: null,
  //       jumpUrl: null,
  //       description: null,
  //       modifiedBy: null,
  //       createdBy: null,
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 281,
  //       name: null,
  //       country: null,
  //       client: null,
  //       platform: null,
  //       position: null,
  //       length: null,
  //       width: null,
  //       status: 1,
  //       imageUrl: null,
  //       jumpUrl: null,
  //       description: null,
  //       modifiedBy: null,
  //       createdBy: null,
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 282,
  //       name: null,
  //       country: null,
  //       client: null,
  //       platform: null,
  //       position: null,
  //       length: null,
  //       width: null,
  //       status: 0,
  //       imageUrl: null,
  //       jumpUrl: null,
  //       description: null,
  //       modifiedBy: null,
  //       createdBy: null,
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 283,
  //       name: '90',
  //       country: 'US',
  //       client: '123',
  //       platform: 'web',
  //       position: 'homepage',
  //       length: 100,
  //       width: 50,
  //       status: 0,
  //       imageUrl: 'http://www.baidu.com',
  //       jumpUrl: null,
  //       description: '',
  //       modifiedBy: 'igscore',
  //       createdBy: 'igscore',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 363,
  //       name: 'test_banner ',
  //       country: 'US',
  //       client: '123',
  //       platform: 'web',
  //       position: 'football_homepage',
  //       length: 100,
  //       width: 100,
  //       status: 0,
  //       imageUrl: '\thttps://static.aiscore.com/_nuxt/img/banner.dd0e2ed.png',
  //       jumpUrl: null,
  //       description: 'test image',
  //       modifiedBy: 'igscore',
  //       createdBy: 'igscore',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 364,
  //       name: 'test_banner ',
  //       country: 'US',
  //       client: '123',
  //       platform: 'web',
  //       position: 'football_homepage',
  //       length: 100,
  //       width: 100,
  //       status: 0,
  //       imageUrl: 'https://static.aiscore.com/_nuxt/img/banner.dd0e2ed.png',
  //       jumpUrl: null,
  //       description: 'test image',
  //       modifiedBy: 'igscore',
  //       createdBy: 'igscore',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 365,
  //       name: 'test_banner ',
  //       country: 'US',
  //       client: '123',
  //       platform: 'web',
  //       position: 'football_homepage',
  //       length: 992,
  //       width: 100,
  //       status: 0,
  //       imageUrl: 'https://static.aiscore.com/_nuxt/img/banner.dd0e2ed.png',
  //       jumpUrl: null,
  //       description: 'test image',
  //       modifiedBy: 'igscore',
  //       createdBy: 'igscore',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 366,
  //       name: 'test_banner ',
  //       country: 'CN',
  //       client: '123',
  //       platform: 'web',
  //       position: 'football_homepage',
  //       length: 992,
  //       width: 100,
  //       status: 0,
  //       imageUrl: 'https://static.aiscore.com/_nuxt/img/banner.dd0e2ed.png',
  //       jumpUrl: null,
  //       description: 'test image',
  //       modifiedBy: 'igscore',
  //       createdBy: 'igscore',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 367,
  //       name: '90',
  //       country: 'US',
  //       client: '123',
  //       platform: 'web',
  //       position: 'homepage',
  //       length: 500,
  //       width: 100,
  //       status: 0,
  //       imageUrl: 'http://www.baidu.com',
  //       jumpUrl: 'http://www.baidu.com',
  //       description: 'width 500，height100',
  //       modifiedBy: 'igscore',
  //       createdBy: 'igscore',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 368,
  //       name: 'web home',
  //       country: 'US',
  //       client: '123',
  //       platform: 'web',
  //       position: 'homepage',
  //       length: 100,
  //       width: 992,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/Interwin_Gif_992x100.gif',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: 'igscore',
  //       createdBy: 'igscore',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 369,
  //       name: '90',
  //       country: 'US',
  //       client: '123',
  //       platform: 'web',
  //       position: 'homepage',
  //       length: 500,
  //       width: 100,
  //       status: 0,
  //       imageUrl: 'http://www.baidu.com',
  //       jumpUrl: 'http://www.baidu.com',
  //       description: 'width 500，height,100',
  //       modifiedBy: 'igscore',
  //       createdBy: 'igscore',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 370,
  //       name: '90',
  //       country: 'US',
  //       client: '123',
  //       platform: 'web',
  //       position: 'homepage',
  //       length: 500,
  //       width: 100,
  //       status: 0,
  //       imageUrl: 'http://www.baidu.com',
  //       jumpUrl: 'http://www.baidu.com',
  //       description: 'width 500，height === 100',
  //       modifiedBy: 'igscore',
  //       createdBy: 'igscore',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 379,
  //       name: '1212',
  //       country: 'US',
  //       client: '123',
  //       platform: 'web',
  //       position: 'homepage',
  //       length: 100,
  //       width: 992,
  //       status: 0,
  //       imageUrl: 'https://www.igscore.com/static-images/ads/pdf.png',
  //       jumpUrl: '1212',
  //       description: '1212',
  //       modifiedBy: 'igAdmin',
  //       createdBy: 'igAdmin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 380,
  //       name: 'iOS live',
  //       country: 'US',
  //       client: '123',
  //       platform: 'ios',
  //       position: 'liveMatch',
  //       length: 100,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/Interwin_Gif_992x100.gif',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: 'igAdmin',
  //       createdBy: 'igAdmin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 389,
  //       name: 'android live',
  //       country: 'US',
  //       client: '123',
  //       platform: 'android',
  //       position: 'liveMatch',
  //       length: 100,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/Interwin_Gif_992x100.gif',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: 'igAdmin',
  //       createdBy: 'igAdmin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //     {
  //       id: 390,
  //       name: 'mobile home',
  //       country: 'US',
  //       client: '123',
  //       platform: 'mobile',
  //       position: 'liveTop',
  //       length: 88,
  //       width: 750,
  //       status: 1,
  //       imageUrl: 'https://files.sitestatic.net/livescore/uploaded/Interwin_Gif_992x100.gif',
  //       jumpUrl: 'https://www.interwinvip.com',
  //       description: 'banner',
  //       modifiedBy: 'igAdmin',
  //       createdBy: 'igAdmin',
  //       startTime: null,
  //       endTime: null,
  //     },
  //   ],
  //   server_time: 1677510294,
  // };
  // axios.post('https://api.igscore.com:8080/v1/common/match/live/count', {"noGameType":true,"lang":"en","timeZone":"+08:00","platform":"web","agentType":null,"appVersion":null,"sign":null})
  return igsRequest.get('user/ad/list');
};

export const goLogin = async ({ username, password }: any) => {
  return igsRequest.post(`doLogin?username=${username}&password=${password}`);
};

export const createAd = async (params: any) => {
  return igsRequest.post(
    'user/ad/create',
    Object.assign(params, {
      client: '123',
      createdBy: 'admin',
    }),
  );
};

export const updateAd = async (params: any) => {
  return igsRequest.post(
    'user/ad/update',
    Object.assign(params, {
      client: '123',
      modifiedBy: 'admin',
    }),
  );
};

export const getAdDetail = async (id: string) => {
  // return {"code":"A00000","message":"Success.","result":{"id":470972,"name":"abcd","country":"CN","client":"123","platform":"web","position":"homepage","length":300,"width":100,"status":1,"imageUrl":"http://fasdfasf","description":"web home page","modifiedBy":"igscore","createdBy":"igscore","startTime":1672924629,"endTime":1794431829},"server_time":1676205155}
  return igsRequest.get(`user/ad/${id}`);
};

export const goLogout = async () => {
  return igsRequest.post('logout');
};
